### ISSUE TITLE
Cannot build: makeapi.py errors

### ISSUE THREAD

**Issue by webdeck** [jedimatt42/fcmd#14]
It looks like the BANK_ definition has changed and makeapi.py no longer works:

```rm -f api.asm
for f in `cat api.lst`; do grep $f b*.h; done | grep BANK_ | cut -d'(' -f2 | cut -d',' -f1-2 >api.banks
python2 makeapi.py api.lst api.banks api.asm
Traceback (most recent call last):
  File "makeapi.py", line 31, in <module>
    api_asm.write("\tref\t{}\n".format(n))
ValueError: zero length field name in format
make: *** [api.asm] Error 1
```

**Comment by webdeck** [comment]
I tried to work around this by looking at how the file history changed, and while I got something to compile, the FCMDC.bin file is 131072 bytes instead of 63363 bytes and it crashes when running the COPY command, so my workaround didn't work.

What do the correct api.banks and api.asm look like?  I have attached the ones I created via hackery.
[api.asm.txt](https://github.com/jedimatt42/fcmd/files/5324581/api.asm.txt)
[api.banks.txt](https://github.com/jedimatt42/fcmd/files/5324582/api.banks.txt)

**Comment by jedimatt42** [comment]
It is a 128K ROM now... I've just merged out some work I've been doing on a branch... 

this API is not 'released' I reserve the right to break compatibility with it still... but some of it works. I don't plan to release the API until version 2.0 

The merge out code improved copy and checksum commands to read 17 blocks per operation, so there should be much less seeking.

I've change a lot of the api generation code... and the scripts are python3 now... I just updated the Makefile to be explicit about python3 also

**Comment by webdeck** [comment]
Thanks - I'm not trying to use the API, I'm just trying to build the project so that I can experiment with it, and I can't build it successfully.  Is there a different branch that I should be using?

**Comment by webdeck** [comment]
Your latest commits fixed this.  I can now build successfully.
