### ISSUE TITLE
line editor needs a jump to start or end of line 

### ISSUE THREAD

**Issue by arcadeshopper** [jedimatt42/fcmd#25]
when editing a long line especially from the buffer it would be nice to jump to the end or the start with a key.. i beleve gkxb used control keys to go to the start and end of the line..  ctl s and ctl d also rxb does and xb28 does similar

**Comment by jedimatt42** [comment]
ctrl-s conflicts with what I had for 'save' but I've changed that to ctrl-w for 'write file'

works in ED and command line

in release 1.27 ( not out yet )  ctrl-c is broken
