### ISSUE TITLE
Sound issue using AUTOCMD

### ISSUE THREAD

**Issue by Omega-TI** [jedimatt42/fcmd#5]
When using the AUTOCMD version, with a single command, in this case CLS, the program makes a continual noise.

**Comment by Omega-TI** [comment]
I found that adding the command TIPIBEEPS to the AUTOCMD sound file corrects the issue.

**Comment by jedimatt42** [comment]
Should be fixed by https://github.com/jedimatt42/fcmd/blob/5e2bd55dd8e418acff75d3c235f7994e7ef4f55e/b0_main.c#L112

commit 6a7b16007e5affb1638b241a94e54c3e73bb9071
